# Generated by Django 4.2.28 on 2026-05-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0003_trainee_eligible_for_placement_trainee_placed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Retained', 'Retained'), ('Left', 'Left')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retentions', to='onboarding.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Appeared', 'Appeared'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='onboarding.trainee')),
            ],
        ),
    ]
