# Generated by Django 4.2.28 on 2026-05-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retention',
            old_name='status',
            new_name='retention_status',
        ),
    ]
