# Generated by Django 4.2.28 on 2026-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_rename_status_retention_retention_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='appeared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='current_household_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='designation_offered',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='salary_ctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retention',
            name='retention_status',
            field=models.CharField(choices=[('Retained', 'Retained'), ('Dropped', 'Dropped'), ('Changed', 'Changed')], max_length=20),
        ),
    ]
