# Generated by Django 4.2.28 on 2026-06-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_trainee_eligible_for_placement_trainee_placed_and_more'),
        ('placement', '0003_interview_appeared_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retention',
            unique_together={('trainee', 'month_number')},
        ),
    ]
