# Generated by Django 4.2.28 on 2026-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_retention_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='place_of_posting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
