# Generated by Django 4.2.28 on 2026-04-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobilization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Decision Pending', 'Decision Pending')], max_length=20)),
                ('slot', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('counselled_by_name', models.CharField(max_length=100)),
                ('counselled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_logs', to=settings.AUTH_USER_MODEL)),
                ('mobilization_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_log', to='mobilization.mobilizationrecord')),
            ],
        ),
    ]
