# Generated by Django 4.2.28 on 2026-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellinglog',
            name='enrolled_flag',
            field=models.BooleanField(default=False),
        ),
    ]
