# Generated by Django 4.2.28 on 2026-04-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('caste', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=10)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('ward_no', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('added_by_name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('exam_name', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('grade', models.CharField(max_length=20)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='mobilization.mobilizationrecord')),
            ],
        ),
    ]
