# Generated by Django 4.2.28 on 2026-05-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationrecord',
            name='counselling_converted',
            field=models.BooleanField(default=False),
        ),
    ]
