# Generated by Django 4.2.28 on 2026-05-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0003_trainee_eligible_for_placement_trainee_placed_and_more'),
        ('teachers', '0001_initial'),
        ('batches', '0002_batch_modules_completed_batch_total_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField()),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('assessment_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='batches.batch')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='teachers.teacher')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='onboarding.trainee')),
            ],
        ),
    ]
