# Generated by Django 4.2.28 on 2026-05-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_modules_completed_batch_total_modules'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='score',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assignments_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='attendance_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_performance_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='viva_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='written_exam_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('Fail', 'Fail')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theory_hrs', models.PositiveIntegerField()),
                ('practical_hrs', models.PositiveIntegerField()),
                ('ssc_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Going On', 'Going On'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='batches.batch')),
            ],
        ),
    ]
