# Generated by Django 4.2.28 on 2026-06-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_modules_completed_batch_total_modules'),
        ('trainer', '0002_remove_assessment_score_assessment_assignments_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='attendance_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='ssc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('total_marks', models.FloatField(default=0)),
                ('theory_marks', models.FloatField(default=0)),
                ('skills_marks', models.FloatField(default=0)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Going On', 'Going On'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_criteria', to='batches.batch')),
            ],
        ),
        migrations.CreateModel(
            name='InternalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theory_marks', models.PositiveIntegerField(default=0)),
                ('practical_marks', models.PositiveIntegerField(default=0)),
                ('project_marks', models.PositiveIntegerField(default=0)),
                ('viva_marks', models.PositiveIntegerField(default=0)),
                ('weightage_percent', models.PositiveIntegerField(default=0)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Going On', 'Going On'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_assessments', to='batches.batch')),
            ],
        ),
    ]
