# Generated by Django 4.2.28 on 2026-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_module_attendance_score_module_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Going On', 'Going On'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
