# Generated by Django 4.2.28 on 2026-05-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mobilizer', 'Mobilizer'), ('counsellor', 'Counsellor'), ('teacher', 'Teacher'), ('trainer', 'Trainer'), ('placement_officer', 'Placement Officer'), ('trainee', 'Trainee')], max_length=20),
        ),
    ]
