# Generated by Django 4.2.28 on 2026-04-11 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counselling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=50, unique=True)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('center', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('ward_no', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('slot', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('counselled_by_name', models.CharField(max_length=100)),
                ('counselling_date', models.DateField()),
                ('caste', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=14, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(choices=[('Fresher', 'Fresher'), ('Job', 'Job'), ('Studying', 'Studying'), ('Housewife', 'Housewife'), ('Business', 'Business'), ('Others', 'Others')], max_length=20)),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('personal_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_of_entry', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('counselling_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='counselling.counsellinglog')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
