# Generated by Django 4.2.28 on 2026-04-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slot', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('domain', models.CharField(choices=[('Digital Marketing', 'Digital Marketing'), ('Digital Mitra', 'Digital Mitra'), ('Retail Sales Associate', 'Retail Sales Associate'), ('Hospitality Management', 'Hospitality Management'), ('Logistics and Warehousing', 'Logistics and Warehousing'), ('Industrial Sewing', 'Industrial Sewing')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='teachers.teacher')),
            ],
        ),
    ]
