# Generated by Django 4.2.28 on 2026-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='modules_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_modules',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
