# Generated by Django 4.2.28 on 2026-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_modules_completed_batch_total_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='domain',
            field=models.CharField(choices=[('Digital Marketing', 'Digital Marketing'), ('Digital Mitra', 'Digital Mitra'), ('Retail Sales Associate', 'Retail Sales Associate'), ('Hospitality Management', 'Hospitality Management'), ('Logistics and Warehousing', 'Logistics and Warehousing'), ('Industrial Sewing', 'Industrial Sewing')], max_length=50),
        ),
    ]
