# Generated by Django 4.2.28 on 2026-04-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
