# Generated by Django 4.2.28 on 2026-05-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_trainee_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='eligible_for_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainee',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainee',
            name='ssc_certificate_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainee',
            name='training_completed',
            field=models.BooleanField(default=False),
        ),
    ]
