# Generated by Django 4.2.28 on 2026-06-07 18:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('onboarding', '0003_trainee_eligible_for_placement_trainee_placed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='batch',
        ),
        migrations.AddField(
            model_name='trainee',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='batches.batch'),
        ),
    ]
